# -*- coding: utf-8 -*-
"""data stractur in python .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRYGHpu826ErWxQnhwsWds0eGohbbB_o
"""

#Data Structures in python

# إنشاء قائمة


numbers = [10, 20, 30, 40]
# طباعة عنصر
print(numbers[0])     # يطبع 10
# تعديل عنصر
numbers[2] = 99
# إضافة عنصر
numbers.append(50)
# حذف عنصر
numbers.remove(20)
# طباعة القائمة كاملة
print(numbers)


 # إنشاء ومعالجة القوائم
students = ["أحمد", "محمد", "فاطمة"]

# الإضافة
students.append("خالد")        # إضافة في النهاية
students.insert(1, "سارة")     # إضافة في موقع محدد

# الحذف
students.remove("محمد")        # حذف عنصر محدد
last_student = students.pop()  # حذف آخر عنصر

# العمليات
print(len(students))           # عدد العناصر
print(students[0])             # العنصر الأول
print(students[-1])            # العنصر الأخير

# التقطيع (Slicing)
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(numbers[2:5])            # من index 2 إلى 4 ← [3, 4, 5]
print(numbers[:3])             # من البداية إلى 2 ← [1, 2, 3]
print(numbers[7:])             # من 7 إلى النهاية ← [8, 9, 10]


print("===================================\n")

#مثال اخر :

# إنشاء القوائم
empty_list = []
numbers = [1, 2, 3, 4, 5]
mixed = [1, "hello", 3.14, True]
nested = [[1, 2], [3, 4]]

# العمليات الأساسية
fruits = ["apple", "banana", "orange"]

# الوصول للعناصر
print(fruits[0])      # apple (أول عنصر)
print(fruits[-1])     # orange (آخر عنصر)
print(fruits[1:3])    # ['banana', 'orange'] (تقطيع)

# التعديل
fruits[1] = "grape"   # تعديل عنصر
fruits.append("mango") # إضافة في النهاية
fruits.insert(1, "pear") # إضافة في موقع محدد

# الحذف
removed = fruits.pop()    # حذف آخر عنصر
fruits.remove("grape")    # حذف عنصر محدد
del fruits[0]            # حذف بالمؤشر

# الطرق المهمة
fruits.extend(["kiwi", "pineapple"])  # دمج قوائم
fruits.sort()                                       # ترتيب تصاعدي
fruits.reverse()                                     # عكس الترتيب
count = fruits.count("apple")          # عد التكرارات
index = fruits.index("orange")        # معرفة الفهرس

print("-----------------------------------------------------------------------")
# إنشاء الصفوف

point = (3, 5)
print(point[0])     # 3
# محاولة التعديل ستفشل:
# point[0] = 10   خطأ

empty_tuple = ()
single_item = (1,)      # ملاحظة: الفاصلة ضرورية
colors = ("red", "green", "blue")
mixed = (1, "hello", 3.14, True)

# الوصول للعناصر
print(colors[0])        # red
print(colors[-1])       # blue
print(colors[1:3])      # ('green', 'blue')

# العمليات (لا يمكن التعديل مباشرة)
# colors[0] = "yellow"  # خطأ! لا يمكن التعديل

# لكن يمكن:
new_colors = colors + ("yellow",)  # دمج
repeated = colors * 2              # تكرار

# الطرق المحدودة
index = colors.index("green")      # 1
count = colors.count("red")        # 1

# فك الصفوف (Unpacking)
point = (10, 20)
x, y = point
print(f"x: {x}, y: {y}")          # x: 10, y: 20

# استخدام كقيم مرجعة من الدوال
def get_user_info():
    return "hussam", 28 , "sanaa"

name, age, city = get_user_info()

print("----------------------------------------------------------------------")
