# -*- coding: utf-8 -*-
"""data stractur in python .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRYGHpu826ErWxQnhwsWds0eGohbbB_o
"""

#Data Structures in python

# إنشاء قائمة


numbers = [10, 20, 30, 40]
# طباعة عنصر
print(numbers[0])     # يطبع 10
# تعديل عنصر
numbers[2] = 99
# إضافة عنصر
numbers.append(50)
# حذف عنصر
numbers.remove(20)
# طباعة القائمة كاملة
print(numbers)


 # إنشاء ومعالجة القوائم
students = ["أحمد", "محمد", "فاطمة"]

# الإضافة
students.append("خالد")        # إضافة في النهاية
students.insert(1, "سارة")     # إضافة في موقع محدد

# الحذف
students.remove("محمد")        # حذف عنصر محدد
last_student = students.pop()  # حذف آخر عنصر

# العمليات
print(len(students))           # عدد العناصر
print(students[0])             # العنصر الأول
print(students[-1])            # العنصر الأخير

# التقطيع (Slicing)
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(numbers[2:5])            # من index 2 إلى 4 ← [3, 4, 5]
print(numbers[:3])             # من البداية إلى 2 ← [1, 2, 3]
print(numbers[7:])             # من 7 إلى النهاية ← [8, 9, 10]


print("===================================\n")

#مثال اخر :

# إنشاء القوائم
empty_list = []
numbers = [1, 2, 3, 4, 5]
mixed = [1, "hello", 3.14, True]
nested = [[1, 2], [3, 4]]

# العمليات الأساسية
fruits = ["apple", "banana", "orange"]

# الوصول للعناصر
print(fruits[0])      # apple (أول عنصر)
print(fruits[-1])     # orange (آخر عنصر)
print(fruits[1:3])    # ['banana', 'orange'] (تقطيع)

# التعديل
fruits[1] = "grape"   # تعديل عنصر
fruits.append("mango") # إضافة في النهاية
fruits.insert(1, "pear") # إضافة في موقع محدد

# الحذف
removed = fruits.pop()    # حذف آخر عنصر
fruits.remove("grape")    # حذف عنصر محدد
del fruits[0]            # حذف بالمؤشر

# الطرق المهمة
fruits.extend(["kiwi", "pineapple"])  # دمج قوائم
fruits.sort()                                       # ترتيب تصاعدي
fruits.reverse()                                     # عكس الترتيب
count = fruits.count("apple")          # عد التكرارات
index = fruits.index("orange")        # معرفة الفهرس

print("-----------------------------------------------------------------------")
# إنشاء الصفوف

point = (3, 5)
print(point[0])     # 3
# محاولة التعديل ستفشل:
# point[0] = 10   خطأ

empty_tuple = ()
single_item = (1,)      # ملاحظة: الفاصلة ضرورية
colors = ("red", "green", "blue")
mixed = (1, "hello", 3.14, True)

# الوصول للعناصر
print(colors[0])        # red
print(colors[-1])       # blue
print(colors[1:3])      # ('green', 'blue')

# العمليات (لا يمكن التعديل مباشرة)
# colors[0] = "yellow"  # خطأ! لا يمكن التعديل

# لكن يمكن:
new_colors = colors + ("yellow",)  # دمج
repeated = colors * 2              # تكرار

# الطرق المحدودة
index = colors.index("green")      # 1
count = colors.count("red")        # 1

# فك الصفوف (Unpacking)
point = (10, 20)
x, y = point
print(f"x: {x}, y: {y}")          # x: 10, y: 20

# استخدام كقيم مرجعة من الدوال
def get_user_info():
    return "hussam", 28 , "sanaa"

name, age, city = get_user_info()

print("----------------------------------------------------------------------")

# إنشاء القواميس
empty_dict = {}
student = {
    "name": "أحمد",
    "age": 20,
    "grades": [85, 90, 78],
    "courses": {
        "math": 95,
        "science": 88
    }
}

# الوصول للقيم
print(student["name"])           # أحمد
print(student.get("age"))        # 20
print(student.get("phone", "غير موجود")) # قيمة افتراضية

# الإضافة والتعديل
student["city"] = "الرياض"       # إضافة جديدة
student["age"] = 21              # تعديل موجود

# الحذف
phone = student.pop("city")      # حذف وإرجاع القيمة
del student["grades"]           # حذف مباشر

# الطرق المهمة
keys = student.keys()           # جميع المفاتيح
values = student.values()       # جميع القيم
items = student.items()         # جميع الأزواج

# التكرار على القاموس
for key, value in student.items():
    print(f"{key}: {value}")

# التحقق من الوجود
if "name" in student:
    print("المفتاح موجود")

# دمج القواميس
additional_info = {"phone": "0555555555", "email": "test@example.com"}
student.update(additional_info)

print("===================================\n")
#أيضا مثال عملي اخر :

person = {
    "name": "Hussam",
    "age": 28,
    "city": "Sana'a"
}
print(person["name"])      # Hussam

# تعديل قيمة
person["age"] = 26

# إضافة مفتاح جديد
person["job"] = "Engineer"

# حذف مفتاح
del person["city"]

print(person)
print("===================================\n")

"""
ملاحظات:
•	المفتاح يجب أن يكون فريدًا.
•	مفيد جدًا لتخزين البيانات المنظمة مثل ملفات JSON ."""

# إنشاء قاموس
car = {
    "brand": "تويوتا",
    "model": "كامري",
    "year": 2022,
    "colors": ["أبيض", "أسود", "فضي"]
}

# الوصول للقيم
print(car["brand"])            # تويوتا
print(car.get("model"))        # كامري

# التعديل والإضافة
car["year"] = 2023             # تحديث قيمة
car["price"] = 90000           # إضافة مفتاح جديد

# الحذف
del car["colors"]              # حذف مفتاح
year = car.pop("year")         # حذف وإرجاع القيمة

# التكرار على القاموس
for key, value in car.items():
    print(f"{key}: {value}")

print("-----------------------------------------------------------------------")

# إنشاء المجموعات
empty_set = set()
numbers = {1, 2, 3, 4, 5}
duplicates = {1, 2, 2, 3, 3, 4} # يصبح {1, 2, 3, 4}
# العمليات الأساسية
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# الإضافة والحذف
set1.add(6)             # إضافة عنصر
set1.remove(3)          # حذف عنصر (يسبب خطأ إذا غير موجود)
set1.discard(10)        # حذف عنصر (لا يسبب خطأ)
popped = set1.pop()     # حذف عنصر عشوائي

# عمليات المجموعات
union = set1 | set2          # الاتحاد {1,2,3,4,5,6,7,8}
intersection = set1 & set2   # التقاطع {4,5}
difference = set1 - set2     # الفرق {1,2,3}
symmetric_diff = set1 ^ set2 # الفرق المتماثل {1,2,3,6,7,8}

# العلاقات
is_subset = {1, 2}.issubset(set1)        # True
is_superset = set1.issuperset({1, 2})    # True
is_disjoint = {1, 2}.isdisjoint({7, 8})  # True

print("===================================\n")
#مثال عملي اخر :

colors = {"red", "blue", "green", "blue"}
print(colors)   # {'red', 'blue', 'green'}
# إضافة عنصر
colors.add("yellow")

# إزالة عنصر
colors.remove("red")
print("===================================\n")
"""
تمرين تطبيقي
اكتب برنامجًا يخزّن معلومات 3 طلاب (الاسم، العمر، التخصص) داخل قائمة من القواميس، ثم يطبعها بطريقة مرتبة.
"""

students = [
    {"name": "Ali", "age": 20, "major": "AI"},
    {"name": "Sara", "age": 22, "major": "CS"},
    {"name": "Omar", "age": 21, "major": "IT"}
]
for student in students:
  print(f"الاسم: {student['name']} - العمر: {student['age']} - التخصص: {student['major']}")

"""
السلاسل النصية (Strings)
 سلسلة من الأحرف
•	الخصائص:
o	مرتبة
o	غير قابلة للتعديل
o	قابلة للتكرار
o	تدعم التقطيع والفهرسة
"""

# إنشاء السلاسل
name = "أحمد"
message = 'مرحبا بالعالم'
multiline = """هذا نص
متعدد الأسطر"""

# العمليات الأساسية
text = "Python Programming"


# الفهرسة والتقطيع
print(text[0])      # P
print(text[-1])     # g
print(text[0:6])    # Python
print(text[7:])     # Programming
# الطرق المهمة
upper_text = text.upper()           # PYTHON PROGRAMMING
lower_text = text.lower()           # python programming
words = text.split()                # ['Python', 'Programming']
joined = " ".join(words)            # 'Python Programming'
replaced = text.replace("Python", "Java") # Java Programming
# الفحص
starts = text.startswith("Python")  # True
ends = text.endswith("ing")         # True
contains = "gram" in text           # True
# التنسيق
name = "محمد"
age = 25
formatted = f"الاسم: {name}, العمر: {age}" # التنسيق الحديث
old_format = "الاسم: {}, العمر: {}".format(name, age)

print("===================================\n")