# -*- coding: utf-8 -*-
"""Inheritance in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Hussam780/f0d14af70fb5139c0ea2ec5da5eba82d/untitled10.ipynb

## الوراثة في بايثون (Inheritance in Python)

الوراثة هي مبدأ أساسي في البرمجة الشيئية (Object-Oriented Programming) يسمح لفئة (Class) جديدة (تسمى الفئة الفرعية أو المشتقة أو الابنة - `child class`/`derived class`) باكتساب الخصائص (attributes) والسلوكيات (methods) من فئة موجودة (تسمى الفئة الأساسية أو الرئيسية أو الأم - `parent class`/`base class`).

**فوائد الوراثة:**
1.  **إعادة استخدام الكود (Code Reusability):** يمكنك استخدام الكود المكتوب في الفئة الأم دون الحاجة لإعادة كتابته.
2.  **تنظيم الكود:** تساعد في تنظيم الكود في تسلسل هرمي منطقي.
3.  **قابلية التوسيع (Extensibility):** يمكن بسهولة توسيع وظائف البرنامج بإضافة فئات فرعية جديدة.

**كيف تعمل الوراثة في بايثون؟**
تُحدد الفئة الفرعية الفئة الأم في تعريفها داخل الأقواس. إليك مثال بسيط على البنية:

```python
class ParentClass:
    # خصائص ووظائف الفئة الأم
    pass

class ChildClass(ParentClass):
    # خصائص ووظائف الفئة الفرعية
    # يمكنها أيضاً تجاوز (override) وظائف الفئة الأم أو إضافة وظائف جديدة
    pass
```

الآن، لننتقل إلى مثال عملي لإدارة الطلاب.

### مثال عملي: نظام إدارة الطلاب باستخدام الوراثة

### أنواع الوراثة في بايثون:

**1. الوراثة الفردية (Single Inheritance):**
هي أبسط أنواع الوراثة، حيث ترث فئة فرعية واحدة من فئة أساسية واحدة فقط. المثال الذي قدمته سابقاً لنظام إدارة الطلاب هو مثال على الوراثة الفردية، حيث ترث `Student` و `Instructor` من `Person`.
"""

class Person:
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender

    def get_details(self):
        return f"الاسم: {self.name}, العمر: {self.age}, الجنس: {self.gender}"

    def introduce(self):
        return f"أهلاً، أنا {self.name}."


class Student(Person):
    def __init__(self, name, age, gender, student_id, major):
        super().__init__(name, age, gender)  # استدعاء مُنشئ الفئة الأم
        self.student_id = student_id
        self.major = major
        self.courses = []

    def get_details(self):
        # تجاوز (override) وظيفة get_details من الفئة الأم وإضافة تفاصيل الطالب
        parent_details = super().get_details()
        return f"{parent_details}, رقم الطالب: {self.student_id}, التخصص: {self.major}"

    def enroll_course(self, course_name):
        if course_name not in self.courses:
            self.courses.append(course_name)
            return f"{self.name} تم تسجيله في مقرر {course_name}."
        else:
            return f"{self.name} مسجل بالفعل في مقرر {course_name}."

    def list_courses(self):
        if not self.courses:
            return f"{self.name} لم يسجل في أي مقررات بعد."
        return f"{self.name} مسجل في المقررات التالية: {', '.join(self.courses)}."


class Instructor(Person):
    def __init__(self, name, age, gender, employee_id, department):
        super().__init__(name, age, gender)
        self.employee_id = employee_id
        self.department = department
        self.assigned_courses = []

    def get_details(self):
        # تجاوز (override) وظيفة get_details من الفئة الأم وإضافة تفاصيل المدرس
        parent_details = super().get_details()
        return f"{parent_details}, رقم الموظف: {self.employee_id}, القسم: {self.department}"

    def assign_course(self, course_name):
        if course_name not in self.assigned_courses:
            self.assigned_courses.append(course_name)
            return f"{self.name} تم تكليفه بتدريس مقرر {course_name}."
        else:
            return f"{self.name} مكلف بالفعل بتدريس مقرر {course_name}."

    def list_assigned_courses(self):
        if not self.assigned_courses:
            return f"{self.name} لم يتم تكليفه بأي مقررات بعد."
        return f"{self.name} مكلف بتدريس المقررات التالية: {', '.join(self.assigned_courses)}."


# إنشاء كائنات (Objects) من الفئات
student1 = Student("أحمد", 20, "ذكر", "S001", "علوم الحاسوب")
student2 = Student("فاطمة", 21, "أنثى", "S002", "هندسة البرمجيات")

instructor1 = Instructor("د. علي", 45, "ذكر", "I101", "علوم الحاسوب")

# عرض التفاصيل والقيام بعمليات
print("\n--- تفاصيل الطلاب ---")
print(student1.introduce())
print(student1.get_details())
print(student1.enroll_course("مقدمة في البرمجة"))
print(student1.enroll_course("هياكل البيانات"))
print(student1.list_courses())

print("\n")
print(student2.introduce())
print(student2.get_details())
print(student2.enroll_course("تصميم الويب"))
print(student2.list_courses())

print("\n--- تفاصيل المدرسين ---")
print(instructor1.introduce())
print(instructor1.get_details())
print(instructor1.assign_course("مقدمة في البرمجة"))
print(instructor1.assign_course("تصميم قواعد البيانات"))
print(instructor1.list_assigned_courses())


# مثال على كيفية إدارة قائمة من الأشخاص
print("\n--- قائمة الأشخاص في النظام ---")
people = [student1, student2, instructor1]

for person in people:
    print(f"نوع الكائن: {type(person).__name__}")
    print(person.get_details())
    if isinstance(person, Student):
        print(person.list_courses())
    elif isinstance(person, Instructor):
        print(person.list_assigned_courses())
    print("-" * 30)

"""---

### 2. الوراثة المتعددة (Multiple Inheritance):

في الوراثة المتعددة، يمكن لفئة فرعية أن ترث من فئات أساسية متعددة. هذا يعني أن الفئة الفرعية تكتسب الخصائص والوظائف من جميع الفئات الأم.

**مثال:** لنفترض أن لدينا فئة `CanSwim` وفئة `CanFly`. يمكننا إنشاء فئة `Duck` (البطة) ترث من كلتيهما، لأن البطة يمكنها السباحة والطيران.
"""

class CanSwim:
    def swim(self):
        return "أستطيع السباحة."

class CanFly:
    def fly(self):
        return "أستطيع الطيران."

class Duck(CanSwim, CanFly):
    def quack(self):
        return "أنا بطة وأقول: بط بط!"

# إنشاء كائن من فئة Duck
duck = Duck()
print("--- الوراثة المتعددة ---")
print(duck.quack())
print(duck.swim())
print(duck.fly())
print("-" * 30)

"""---

### 3. الوراثة متعددة المستويات (Multilevel Inheritance):

في هذا النوع، فئة ترث من فئة أخرى، وهذه الفئة الأخرى ترث من فئة ثالثة، وهكذا. يتم إنشاء سلسلة من الوراثة.

**مثال:** لدينا `Vehicle` (مركبة)، ثم `Car` (سيارة) ترث من `Vehicle`، ثم `SportsCar` (سيارة رياضية) ترث من `Car`.
"""

class Vehicle:
    def __init__(self, brand):
        self.brand = brand

    def get_brand(self):
        return f"الماركة: {self.brand}"

class Car(Vehicle):
    def __init__(self, brand, model):
        super().__init__(brand)
        self.model = model

    def get_model(self):
        return f"الموديل: {self.model}"

class SportsCar(Car):
    def __init__(self, brand, model, top_speed):
        super().__init__(brand, model)
        self.top_speed = top_speed

    def get_top_speed(self):
        return f"السرعة القصوى: {self.top_speed} كم/ساعة"

# إنشاء كائن من فئة SportsCar
sports_car = SportsCar("Ferrari", "488 GTB", 330)
print("--- الوراثة متعددة المستويات ---")
print(sports_car.get_brand())
print(sports_car.get_model())
print(sports_car.get_top_speed())
print("-" * 30)

"""---

### 4. الوراثة الهرمية (Hierarchical Inheritance):

في هذا النوع، ترث عدة فئات فرعية من فئة أساسية واحدة. الفئة الأساسية تعمل كأصل للعديد من الفئات الفرعية.

**مثال:** لدينا فئة `Animal` (حيوان)، وترث منها `Dog` (كلب) و `Cat` (قطة) و `Bird` (طائر).
"""

class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        return "أصدر صوتاً."

class Dog(Animal):
    def speak(self):
        return f"{self.name} ينبح: هاو هاو!"

class Cat(Animal):
    def speak(self):
        return f"{self.name} يموء: مواء مواء!"

class Bird(Animal):
    def speak(self):
        return f"{self.name} يغرد: زقزقة!"

# إنشاء كائنات من الفئات الفرعية
dog = Dog("بُندق")
cat = Cat("كيتي")
bird = Bird("زوزو")

print("--- الوراثة الهرمية ---")
print(dog.speak())
print(cat.speak())
print(bird.speak())
print("-" * 30)

"""---

### 5. الوراثة المختلطة (Hybrid Inheritance):

هي مزيج من نوعين أو أكثر من أنواع الوراثة المذكورة أعلاه. غالباً ما تكون مزيجاً من الوراثة المتعددة والوراثة الهرمية أو متعددة المستويات.

**مثال:** لنفترض أن لدينا `Person`، وترث منها `Student` و `Teacher`. ثم لدينا فئة `TeachingAssistant` (مساعد تدريس) ترث من `Student` و `Teacher` (وراثة متعددة) وهي نفسها ترث من `Person` (وراثة متعددة المستويات).
"""

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def introduce(self):
        return f"أنا {self.name}, عمري {self.age} سنوات."

class Student(Person):
    def __init__(self, name, age, student_id):
        super().__init__(name, age)
        self.student_id = student_id

    def study(self):
        return f"{self.name} (رقم الطالب: {self.student_id}) يدرس بجد."

class Teacher(Person):
    def __init__(self, name, age, employee_id):
        super().__init__(name, age)
        self.employee_id = employee_id

    def teach(self):
        return f"{self.name} (رقم الموظف: {self.employee_id}) يُدرس الطلاب."

# Hybrid Inheritance: TeachingAssistant يرث من Student و Teacher
class TeachingAssistant(Student, Teacher):
    def __init__(self, name, age, student_id, employee_id, course_assisted):
        # استدعاء مُنشئات الفئات الأم بعناية لتجنب المشاكل (مثلاً، باستخدام MRO)
        Student.__init__(self, name, age, student_id)
        Teacher.__init__(self, name, age, employee_id)
        self.course_assisted = course_assisted

    def assist(self):
        return f"{self.name} يساعد في مقرر {self.course_assisted}."

# إنشاء كائن من TeachingAssistant
ta = TeachingAssistant("سارة", 22, "S003", "E005", "مقدمة في البرمجة")

print("--- الوراثة المختلطة ---")
print(ta.introduce()) # من Person (عبر Student أو Teacher)
print(ta.study())     # من Student
print(ta.teach())     # من Teacher
print(ta.assist())    # من TeachingAssistant نفسها
print(f"ترتيب حل التوابع (MRO) للفئة TeachingAssistant:\n{TeachingAssistant.__mro__}")