# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9fPC9fN9093dOPk-qt4oUArh24V2gLh
"""

# mini_gpt.py
import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import random

# ---------- إعداد بيانات تجريبية صغير ----------
text = "hello world. hello transformer. hello gpt."
chars = sorted(list(set(text)))
vocab_size = len(chars)
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for ch,i in stoi.items()}
data = [stoi[ch] for ch in text]

# تحضير بيانات تدريب بسيطة (سلاسل من الطول seq_len)
def get_batch(batch_size=8, seq_len=8):
    x = torch.zeros((batch_size, seq_len), dtype=torch.long)
    y = torch.zeros((batch_size, seq_len), dtype=torch.long)
    for i in range(batch_size):
        start = random.randint(0, max(0, len(data)-seq_len-1))
        x[i] = torch.tensor(data[start:start+seq_len])
        y[i] = torch.tensor(data[start+1:start+seq_len+1])
    return x, y

# ---------- المكونات الأساسية ----------
class SelfAttention(nn.Module):
    def __init__(self, embed_size, head_dim):
        super().__init__()
        self.query = nn.Linear(embed_size, head_dim, bias=False)
        self.key   = nn.Linear(embed_size, head_dim, bias=False)
        self.value = nn.Linear(embed_size, head_dim, bias=False)
        self.scale = 1.0 / math.sqrt(head_dim)

    def forward(self, x):
        # x: (B, T, E)
        q = self.query(x)
        k = self.key(x)
        v = self.value(x)
        att = torch.matmul(q, k.transpose(-2,-1)) * self.scale  # (B,T,T)
        att = F.softmax(att, dim=-1)
        out = torch.matmul(att, v)  # (B, T, head_dim)
        return out

class MultiHead(nn.Module):
    def __init__(self, embed_size, num_heads):
        super().__init__()
        assert embed_size % num_heads == 0
        self.num_heads = num_heads
        self.head_dim = embed_size // num_heads
        self.heads = nn.ModuleList([SelfAttention(embed_size, self.head_dim) for _ in range(num_heads)])
        self.proj = nn.Linear(embed_size, embed_size)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        return self.proj(out)

class FeedForward(nn.Module):
    def __init__(self, embed_size, ff_hidden):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(embed_size, ff_hidden),
            nn.ReLU(),
            nn.Linear(ff_hidden, embed_size)
        )
    def forward(self, x):
        return self.net(x)

class GPTBlock(nn.Module):
    def __init__(self, embed_size, num_heads, ff_hidden):
        super().__init__()
        self.ln1 = nn.LayerNorm(embed_size)
        self.mha = MultiHead(embed_size, num_heads)
        self.ln2 = nn.LayerNorm(embed_size)
        self.ff = FeedForward(embed_size, ff_hidden)

    def forward(self, x):
        x = x + self.mha(self.ln1(x))
        x = x + self.ff(self.ln2(x))
        return x

class MiniGPT(nn.Module):
    def __init__(self, vocab_size, embed_size=64, n_blocks=2, num_heads=4, ff_hidden=256, max_len=128):
        super().__init__()
        self.token_emb = nn.Embedding(vocab_size, embed_size)
        self.pos_emb = nn.Embedding(max_len, embed_size)
        self.blocks = nn.Sequential(*[GPTBlock(embed_size, num_heads, ff_hidden) for _ in range(n_blocks)])
        self.ln_f = nn.LayerNorm(embed_size)
        self.head = nn.Linear(embed_size, vocab_size)

    def forward(self, idx):
        B, T = idx.shape
        tok = self.token_emb(idx)
        pos = self.pos_emb(torch.arange(T, device=idx.device))[None, :, :]
        x = tok + pos
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.head(x)
        return logits

# ---------- تدريب صغير ----------
device = "cuda" if torch.cuda.is_available() else "cpu"
model = MiniGPT(vocab_size).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)
loss_fn = nn.CrossEntropyLoss()

for iter in range(400):
    x, y = get_batch(batch_size=16, seq_len=8)
    x, y = x.to(device), y.to(device)
    logits = model(x)  # (B,T,V)
    loss = loss_fn(logits.view(-1, vocab_size), y.view(-1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if iter % 50 == 0:
        print(f"iter {iter} loss {loss.item():.4f}")

# ---------- توليد نص (توليد حرفي) ----------
def generate(model, start_str, length=50):
    model.eval()
    idx = torch.tensor([[stoi[ch] for ch in start_str]], dtype=torch.long).to(device)
    for _ in range(length):
        logits = model(idx)
        next_logits = logits[:, -1, :]
        probs = F.softmax(next_logits, dim=-1)
        next_id = torch.multinomial(probs, num_samples=1)
        idx = torch.cat([idx, next_id], dim=1)
    out = "".join(itos[int(i)] for i in idx[0].cpu().numpy())
    return out

print("generated:", generate(model, "hello "))